# Generated by Django 5.2.6 on 2025-09-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.category'),
        ),
        migrations.AddField(
            model_name='collection',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='in_collections', to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='profiles.profile'),
        ),
    ]
